// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twajwqxiwnpvnxotidqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3YWp3cXhpd25wdm54b3RpZHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDIyNTEsImV4cCI6MjA2NDgxODI1MX0.kXpfqNY_V7gyR_ALAqBH8pQRey9wCGAQ9C2ImgrMcvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);